const LANG_ENUM = {
    en: "en",
    cz: "cz",
    de: "de",
    ru: "ru",
    ua: "ua"
}

const STRING_RES = {
    [LANG_ENUM.en]: {
        hello: "Hello!",
        new_update_notification_message: `WalletStats got new update version %s!`,
        this_month: "This month",
        last_month: "Last month",
        other: "Other",
        expense: "Expense",
        expenses: "Expenses",
        income_singular: "Income",
        income_plural: "Income",
        transfer: "Transfer",
        view_all: "View all",
        total: "Total:",
        whats_new_message: "What's new in V",
        date: "Date",
        note: "Note",
        rate: "Rate",
        amount: "Amount",
        final_amount: "Final amount",
        category: "Category",
        note_field_placeholder: "for more specific",
        currency: "Currency",
        balance: "Balance",
        color: "Color",
        from: "From",
        to_time_meaning: "To",
        settings: "Settings",
        version: "Version",
        hide_account_from_top_bar: "Hide account from top-bar",
        account_without_balance: "Account without balance",
        do_not_show_balance: "Do not show balance",
        show_details: "Show details",
        make_record: "Make record",
        repeat: "Repeat",
        remove: "Remove",
        back: "Back",
        close: "Close",
        links: "Links",
        reset_data: "Reset data",
        language: "Language",
        appearance: "Appearance",
        top_margin: "Top margin",
        accounts: "Accounts",
        account: "Account",
        from_account: "From account",
        to_account: "To account",
        remove_account: "Remove account",
        add_account: "Add account",
        save_account: "Save account",
        save_record: "Save record",
        make_transfer: "Make transfer",
        save: "Save",
        confirm: "Confirm",
        this_month_title: "This month",
        last_month_title: "Last month",
        this_week: "This week",
        seven_days: "7 days",
        this_year: "This year",
        last_year: "Last year",
        jan_month: "Jan",
        feb_month: "Feb",
        mar_month: "Mar",
        apr_month: "Apr",
        may_month: "May",
        june_month: "June",
        july_month: "July",
        aug_month: "Aug",
        sept_month: "Sept",
        oct_month: "Oct",
        nov_month: "Nov",
        dec_month: "Dec",
        no_records_this_month_message: "You have no records in this month",
        no_records_last_month_message: "You have no records in previous month",
        no_records_this_period_message: "You have no records in this period",
        disable_scrolling: "Disable scrolling",
        enable_scrolling: "Enable scrolling",
        good_morning: "Good morning!",
        good_afternoon: "Good afternoon!",
        good_evening: "Good evening!",
        greetings_no_expenses_message: "No expenses yet today",
        greetings_expenses_message: "Today you spent %.2f %s",
        account_removing_message: "It will also delete all records connected with this account. It is irreversible action.",
        reset_data_message: "Reset all data (accounts, records, settings), then application will be reloaded.",
        it_is_irreversible_action: "It is irreversible action!",
        language_setting_description: "After setting the new language, web-application will be reloaded.",
        english: "English",
        czech: "Czech",
        german: "German",
        russian: "Russian",
        ukrainian: "Ukrainian",
        off_turn_off_meaning: "Off",
        on_turn_on_meaning: "On",
        enable_blurring: "Enable blurring",
        run_animation_on_start: "Run animation on start",
        auto_adjust_theme: "Auto adjust theme",
        top_margin_setting_description: "Set the top margin for easy viewing of the interface on the screen with notch.",
        notification_sound_setting_description: "Select a sound that will play on internal app notifications.",
        without_sound: "Without sound"
    },
    [LANG_ENUM.cz]: {
        hello: "Ahoj!",
        new_update_notification_message: `WalletStats dostal novou aktualizaci verze %s!`,
        this_month: "Tento měsíc",
        last_month: "Před měsíc",
        other: "Jiný",
        expense: "Výdaj",
        expenses: "Výdaje",
        income_singular: "Příjem",
        income_plural: "Příjmy",
        transfer: "Převod",
        view_all: "Vše",
        total: "Celkem:",
        whats_new_message: "Co je nové ve V",
        date: "Datum",
        note: "Poznámka",
        rate: "Kurz",
        amount: "Částka",
        final_amount: "Konečná částka",
        category: "Kategorie",
        note_field_placeholder: "pro upřesnění",
        currency: "Měna",
        balance: "Zůstatek",
        color: "Barva",
        from: "Od",
        to_time_meaning: "Do",
        settings: "Nastavení",
        version: "Verze",
        hide_account_from_top_bar: "Skrýt účet z horního panelu",
        account_without_balance: "Účet bez zůstatku",
        do_not_show_balance: "Nezobrazovat zůstatek",
        show_details: "Ukázat podrobnosti",
        make_record: "Udělat záznam",
        repeat: "Zopakovat",
        remove: "Smazat",
        back: "Zpátky",
        close: "Zavřít",
        links: "Odkazy",
        reset_data: "Resetovat data",
        language: "Jazyk",
        appearance: "Vzhled",
        top_margin: "Horní okraj",
        accounts: "Účty",
        account: "Účet",
        from_account: "Z účtu",
        to_account: "Na účet",
        remove_account: "Smazat účet",
        add_account: "Přidat účet",
        save_account: "Uložit účet",
        save_record: "Uložit záznam",
        make_transfer: "Udělat převod",
        save: "Uložit",
        confirm: "Potvrdit",
        this_month_title: "Tento měsíc",
        last_month_title: "Minulý měsíc",
        this_week: "Tento týden",
        seven_days: "7 dní",
        this_year: "Tento rok",
        last_year: "Před rok",
        jan_month: "Led",
        feb_month: "Ún",
        mar_month: "Brez",
        apr_month: "Dub",
        may_month: "Kvet",
        jun_month: "Cerv",
        jul_month: "Cerve",
        aug_month: "Srp",
        sept_month: "Září",
        oct_month: "Říj",
        nov_month: "List",
        dec_month: "Pros",
        no_records_this_month_message: "V tomto měsíci nemáte žádné záznamy",
        no_records_last_month_message: "V minulém měsíci nemáte žádné záznamy",
        no_records_this_period_message: "V tomto období nemáte žádné záznamy",
        disable_scrolling: "Vypnout rolování",
        enable_scrolling: "Zapnout rolování",
        good_morning: "Dobré ráno!",
        good_afternoon: "Dobrý den!",
        good_evening: "Dobrý večer!",
        greetings_no_expenses_message: "Dnes ještě nebyly žádné výdaj",
        greetings_expenses_message: "Dnes jste utratil(-a) %.2f %s",
        account_removing_message: "To také smaže všechny záznamy spojené s tímto účtem. Je to nevratná akce.",
        reset_data_message: "Resetovat všechna data (účty, záznamy, nastavení), poté se web-aplikace restartuje.",
        it_is_irreversible_action: "Je to nevratná akce!",
        language_setting_description: "Po nastavení nového jazyka se web-aplikace restartuje.",
        english: "Angličtina",
        czech: "Čeština",
        german: "Němčina",
        russian: "Ruština",
        ukrainian: "Ukrainština",
        off_turn_off_meaning: "Vyp",
        on_turn_on_meaning: "Zap",
        enable_blurring: "Povolit rozmazání",
        run_animation_on_start: "Spustit animaci při spuštění",
        auto_adjust_theme: "Automaticky prizpůsobovat motiv",
        top_margin_setting_description: "Nastavte horní okraj pro snadné prohlížení rozhraní na zářezové obrazovce.",
        notification_sound_setting_description: "Vyberte zvuk, který se přehraje při interních oznámeních aplikace.",
        without_sound: "Bez zvuku"
    },
    [LANG_ENUM.de]: {
        hello: "Hallo!",
        new_update_notification_message: `WalletStats hat ein neues Update auf Version %s!`,
        this_month: "Dieser Monat",
        last_month: "Vormonat",
        other: "Anderer",
        expense: "Spesen",
        expenses: "Spesen",
        income_singular: "Einkommen",
        income_plural: "Einkünfte",
        transfer: "Übersetzung",
        view_all: "Alle",
        total: "Gesamt:",
        whats_new_message: "Was gibt es Neues in V",
        date: "Datum",
        note: "Anmerkung",
        rate: "Anfangsrate",
        amount: "Summe",
        final_amount: "Endbetrag",
        category: "Kategorie",
        note_field_placeholder: "für weitere Einzelheiten",
        currency: "Währung",
        balance: "Bilanz",
        color: "Farbe",
        from: "Von",
        to_time_meaning: "Bis",
        settings: "Einstellungen",
        version: "Version",
        hide_account_from_top_bar: "Konto in der Top-Leiste ausblenden",
        account_without_balance: "Konto ohne Guthaben",
        do_not_show_balance: "Guthaben nicht anzeigen",
        show_details: "Details anzeigen",
        make_record: "Eintrag erstellen",
        repeat: "Wiederholen",
        remove: "Löschen",
        back: "Zurück",
        close: "Schließen",
        links: "Links",
        reset_data: "Daten zurücksetzen",
        language: "Sprachen",
        appearance: "Aussehen",
        top_margin: "Top-margin",
        accounts: "Konten",
        account: "Konto",
        from_account: "Von Konto",
        to_account: "Auf Konto",
        remove_account: "Löschen",
        add_account: "Konto hinzufügen",
        save_account: "Speichern",
        save_record: "Eintrag speichern",
        make_transfer: "Überweisen",
        save: "Speichern",
        confirm: "Bestätigen",
        this_month_title: "Dieser Monat",
        last_month_title: "Vormonat",
        this_week: "Diese Woche",
        seven_days: "7 Tage",
        this_year: "Dieses Jahr",
        last_year: "Vorjahr",
        jan_month: "Jan",
        feb_month: "Feb",
        mar_month: "Mär",
        apr_month: "Apr",
        may_month: "Mai",
        jun_month: "Jun",
        jul_month: "Jul",
        aug_month: "Aug",
        sept_month: "Sep",
        oct_month: "Okt",
        nov_month: "Nov",
        dec_month: "Dez",
        no_records_this_month_message: "Sie haben keine Einträge für diesen Monat",
        no_records_last_month_message: "Sie haben keine Einträge vom letzten Monat",
        no_records_this_period_message: "Sie haben keine Einträge für diesen Zeitraum",
        disable_scrolling: "Scrolling ausschalten",
        enable_scrolling: "Scrolling einschalten",
        good_morning: "Guten Morgen!",
        good_afternoon: "Guten Tag!",
        good_evening: "Guten Abend!",
        greetings_no_expenses_message: "Heute Es wurden noch keine Spesen gemacht",
        greetings_expenses_message: "Heute Sie haben bereits %.2f %s ausgegeben",
        account_removing_message: "Damit werden auch alle mit diesem Konto verbundenen Datensätze gelöscht. Dieser Vorgang kann man nicht rückgängig gemacht werden.",
        reset_data_message: "Das wird alle Daten (Konten, Einträge, Einstellungen) zurücksetzen und die Web-Anwendung neu starten.",
        it_is_irreversible_action: "Dieser Vorgang kann man nicht rückgängig gemacht werden!",
        language_setting_description: "Nach der Installation einer neuen Sprache wird die Webanwendung geladen.",
        english: "Englisch",
        czech: "Tschechisch",
        german: "Deutsch",
        russian: "Russisch",
        ukrainian: "Ukrainisch",
        off_turn_off_meaning: "Aus",
        on_turn_on_meaning: "Ein",
        enable_blurring: "Unschärfe aktivieren",
        run_animation_on_start: "Animation beim Start ausführen",
        auto_adjust_theme: "Thema automatisch anpassen",
        top_margin_setting_description: "Setzen Sie den oberen Abstand, um eine bequeme Ansicht der Benutzeroberfläche auf einem Bildschirm mit Aussparung zu gewährleisten.",
        notification_sound_setting_description: "Wählen Sie einen Ton für interne App-Benachrichtigungen aus.",
        without_sound: "Ohne Ton"
    },
    [LANG_ENUM.ru]: {
        hello: "Привет!",
        new_update_notification_message: `WalletStats получил новое обновление версии %s!`,
        this_month: "Этот месяц",
        last_month: "Предыдущий",
        other: "Другой",
        expense: "Расход",
        expenses: "Расходы",
        income_singular: "Доход",
        income_plural: "Доходы",
        transfer: "Перевод",
        view_all: "Все",
        total: "Всего:",
        whats_new_message: "Что нового в В",
        date: "Дата",
        note: "Примечание",
        rate: "Курс",
        amount: "Сумма",
        final_amount: "Итоговая сумма",
        category: "Категория",
        note_field_placeholder: "для большей конкретики",
        currency: "Валюта",
        balance: "Баланс",
        color: "Цвет",
        from: "От",
        to_time_meaning: "До",
        settings: "Настройки",
        version: "Версия",
        hide_account_from_top_bar: "Скрыть счёт из верхней панели",
        account_without_balance: "Счёт без баланса",
        do_not_show_balance: "Не показывать баланс",
        show_details: "Показать детали",
        make_record: "Сделать запись",
        repeat: "Повторить",
        remove: "Удалить",
        back: "Назад",
        close: "Закрыть",
        links: "Ссылки",
        reset_data: "Сбросить данные",
        language: "Язык",
        appearance: "Внешний",
        top_margin: "Верхний отступ",
        accounts: "Счета",
        account: "Счёт",
        from_account: "Со счёта",
        to_account: "На счёт",
        remove_account: "Удалить",
        add_account: "Добавить счёт",
        save_account: "Сохранить",
        save_record: "Сохранить запись",
        make_transfer: "Сделать перевод",
        save: "Сохранить",
        confirm: "Подтвердить",
        this_month_title: "Этот месяц",
        last_month_title: "Прошлый месяц",
        this_week: "Эта неделя",
        seven_days: "7 дней",
        this_year: "Этот год",
        last_year: "Пред год",
        jan_month: "Янв",
        feb_month: "Фев",
        mar_month: "Мар",
        apr_month: "Апр",
        may_month: "Май",
        jun_month: "Июн",
        jul_month: "Июл",
        aug_month: "Авг",
        sept_month: "Сен",
        oct_month: "Окт",
        nov_month: "Ноя",
        dec_month: "Дек",
        no_records_this_month_message: "У вас нет записей за этот месяц",
        no_records_last_month_message: "У вас нет записей за предыдущий месяц",
        no_records_this_period_message: "У вас нет записей за этот период",
        disable_scrolling: "Выключить прокрутку",
        enable_scrolling: "Включить прокрутку",
        good_morning: "Доброе утро!",
        good_afternoon: "Добрый день!",
        good_evening: "Добрый вечер!",
        greetings_no_expenses_message: "Сегодня еще не было никаких расходов",
        greetings_expenses_message: "Сегодня вы потратили %.2f %s",
        account_removing_message: "Это также удалит все записи, связанные с этим счётом. Это необратимое действие.",
        reset_data_message: "Сбросить все данные (счета, записи, настройки), после чего приложение перезагрузится.",
        it_is_irreversible_action: "Это необратимое действие!",
        language_setting_description: "После установки нового языка веб-приложение будет перезагружено.",
        english: "Английский",
        czech: "Чешский",
        german: "Немецкий",
        russian: "Русский",
        ukrainian: "Украинский",
        off_turn_off_meaning: "Выкл",
        on_turn_on_meaning: "Вкл",
        enable_blurring: "Включить размытие",
        run_animation_on_start: "Запустить анимацию при запуске",
        auto_adjust_theme: "Автоматически адаптировать тему",
        top_margin_setting_description: "Установите верхний отступ для удобного просмотра интерфейса на экране с вырезом.",
        notification_sound_setting_description: "Выберите звук для внутренних уведомлений приложения.",
        without_sound: "Без звука"
    },
    [LANG_ENUM.ua]: {
        hello: "Привіт!",
        new_update_notification_message: `WalletStats отримав нове оновлення версії %s!`,
        this_month: "Цей місяць",
        last_month: "Попередній",
        other: "Інший",
        expense: "Витрата",
        expenses: "Витрати",
        income_singular: "Дохід",
        income_plural: "Доходи",
        transfer: "Переказ",
        view_all: "Все",
        total: "Всього:",
        whats_new_message: "Що нового у В",
        date: "Дата",
        note: "Примітка",
        rate: "Курс",
        amount: "Сума",
        final_amount: "Кінцева сума",
        category: "Категорія",
        note_field_placeholder: "для більшої конкретики",
        currency: "Валюта",
        balance: "Баланс",
        color: "Колір",
        from: "Від",
        to_time_meaning: "До",
        settings: "Налаштування",
        version: "Версія",
        hide_account_from_top_bar: "Приховати рахунок з верхньої панелі",
        account_without_balance: "Рахунок без балансу",
        do_not_show_balance: "Не відображати баланс",
        show_details: "Показати деталі",
        make_record: "Зробити запис",
        repeat: "Повторити",
        remove: "Видалити",
        back: "Назад",
        close: "Закрити",
        links: "Посилання",
        reset_data: "Скинути дані",
        language: "Мова",
        appearance: "Зовнішній",
        top_margin: "Верхній відступ",
        accounts: "Рахунки",
        account: "Рахунок",
        from_account: "З рахунку",
        to_account: "На рахунок",
        remove_account: "Видалити",
        add_account: "Додати рахунок",
        save_account: "Зберегти",
        save_record: "Зберегти запис",
        make_transfer: "Зробити переказ",
        save: "Зберегти",
        confirm: "Підтвердити",
        this_month_title: "Цей місяць",
        last_month_title: "Минулий місяць",
        this_week: "Цей тиждень",
        seven_days: "7 днів",
        this_year: "Цей рік",
        last_year: "Попер рік",
        jan_month: "Січ",
        feb_month: "Лют",
        mar_month: "Бер",
        apr_month: "Квіт",
        may_month: "Трав",
        jun_month: "Черв",
        jul_month: "Лип",
        aug_month: "Серп",
        sept_month: "Вер",
        oct_month: "Жовт",
        nov_month: "Лист",
        dec_month: "Груд",
        no_records_this_month_message: "У вас немає записів за цей місяць",
        no_records_last_month_message: "У вас немає записів за попередній місяць",
        no_records_this_period_message: "У вас немає записів за цей період",
        disable_scrolling: "Вимкнути прокручування",
        enable_scrolling: "Увімкнути прокручування",
        good_morning: "Доброго ранку!",
        good_afternoon: "Доброго дня!",
        good_evening: "Доброго вечора!",
        greetings_no_expenses_message: "Сьогодні ще не було жодних витрат",
        greetings_expenses_message: "Сьогодні ви витратили %.2f %s",
        account_removing_message: "Це також видалить всі записи, пов'язані з цим рахунком. Це незворотня дія.",
        reset_data_message: "Скинути всі дані (рахунки, записи, налаштування), після чого веб-програма буде перезавантажена.",
        it_is_irreversible_action: "Це незворотна дія!",
        language_setting_description: "Після встановлення нової мови веб-додаток буде перезавантажено.",
        english: "Англійська",
        czech: "Чеська",
        german: "Німецька",
        russian: "Російська",
        ukrainian: "Українська",
        off_turn_off_meaning: "Вимк",
        on_turn_on_meaning: "Вкл",
        enable_blurring: "Увімкнути розмиття",
        run_animation_on_start: "Запустити анімацію при запуску",
        auto_adjust_theme: "Автоматично адаптувати тему",
        top_margin_setting_description: "Встановіть верхній відступ для зручного перегляду інтерфейсу на екрані з вирізом.",
        notification_sound_setting_description: "Виберіть звук для внутрішніх сповіщень додатку.",
        without_sound: "Без звуку"
    }
}

function getStrings(lang = LANG_ENUM.en) {
    let stringRes = STRING_RES[lang];
    if (stringRes != null) {
        return stringRes;
    } else {
        return STRING_RES[LANG_ENUM.en];
    }
}